### PR TITLE
Update to v0.15.0

### PR DESCRIPTION
**Pull request by sigma-andex**
**Description of the change**

Backlinking to purescript/purescript#4244

Migrates FFI to ES modules

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by sigma-andex** [comment]
🏓 @JordanMartinez

**Review by JordanMartinez — CHANGES_REQUESTED** [review]
Everything looks good except for the function's arrow syntax.

**Comment by thomashoneyman** [comment]
@JordanMartinez Personally, I don't mind the arrow syntax. We're only restrictive about that in the core libraries; Node can use arrow syntax if it wants IMO.

**Comment by thomashoneyman** [comment]
> @thomashoneyman Why was it decided that we would not use arrow syntax in core? Wouldn't that reason also apply here?

It's to do with library users not having to transpile their code in order to run it on old browsers like IE. The same compatibility concerns apply to Node, but Node has supported arrow syntax well before Node 12 (the oldest LTS version), so this particular one doesn't affect Node users.

**Review by JordanMartinez — APPROVED** [review]

**Comment by JordanMartinez** [comment]
@sigma-andex Looks like we forgot to update the changelog here.

**Pull request merged**
