### PR TITLE
Add Base64Url encoding

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

- Add Base64Url encoding.

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by JordanMartinez** [comment]
@thomashoneyman :ping_pong:

**Comment by thomashoneyman** [comment]
Has Node indicated that they will drop these aliases? What harm do you see in retaining them?

**Comment by JordanMartinez** [comment]
> Has Node indicated that they will drop these aliases? What harm do you see in retaining them?

The UCS2 one not so much, but the binary one is confusing. Per [Node docs](https://nodejs.org/docs/latest-v16.x/api/buffer.html#buffers-and-character-encodings)

> 'binary': Alias for 'latin1'. See [binary strings](https://developer.mozilla.org/en-US/docs/Web/API/DOMString/Binary) for more background on this topic. **The name of this encoding can be very misleading, as all of the encodings listed here convert between strings and binary data** (emphasis mine). For converting between strings and Buffers, typically 'utf8' is the right choice.

**Comment by JordanMartinez** [comment]
Regardless, this is one of those "controversial" changes, and I don't want to be blocked by this. I'll revert the commit.

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
