### PR TITLE
fix typo causing undefined encoding in buffers

### PR DESCRIPTION
**Pull request by justinwoo**
this typo prevents me from using writeStringImpl...

### CODE REVIEW

**Comment by paf31** [comment]
Oops, thanks!

**Comment by paf31** [comment]
I wonder if this should be a breaking change, since it technically changes behavior even though it's a bug fix.

cc @hdgarrood @garyb

**Comment by hdgarrood** [comment]
I'm pretty confident this should be a patch level change. What kind of bug fix doesn't change behaviour?

**Comment by paf31** [comment]
Good point.

**Pull request merged**
