### PR TITLE
Internal -> Buffer; invert MonadBuffer module dependency

### LINKED ISSUE #34: Use Effect.Uncurried for FFI
I think this is worth exploring.

### PR DESCRIPTION
**Pull request by JordanMartinez**
This PR contains three changes:

First. it fixes #34 by updating all FFI to use uncurried functions (e.g. `FnX`/`EffectFnX`) ().

Second, it improves type inference by exposing the API otherwise exposed via the `MonadBuffer` type class in favor of hardcoding the corresponding values for `Buffer` and `ST` in their respective modules (while still implementing everything only once via the `Buffer.purs` file). To reduce breakage, their `MonadBuffer` instances were moved into the `Node/Buffer/Class.purs` file. 

One implication of the second change is that the module dependency has been inverted. Whereas before `Node/Buffer.purs` depended on `Node/Buffer/Class.purs` (i.e. it exposed the Buffer API by re-exported the class and its members), now `Node/Buffer/Class.purs` depends on `Node/Buffer.purs` to import the `Buffer` type used in its API.

Third, the `nullable` dependency was added since using `toMaybe` is simpler than passing in the `Nothing` and `Just` constructors into an FFI and handling the null/undefined possibility in FFI.

Fourth, adds APIs that were missing when I checked with the Node 18 docs. There's likely a few more here and there (e.g. variants of functions if one passes in args of a different type), but I didn't bother to add those.

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by JordanMartinez** [comment]
@thomashoneyman This is probably good for an initial review.

Things to consider:
- what tests should be added for the stuff I added here, if any?
- Should more of the API I added be added to the `MonadBuffer` class?
- It's kind of hard to verify that I've added all APIs because they are spread out across 3 modules: Buffer, ImmutableBuffer, and Encoding. It's not clear to me why this was done this way, nor whether it should be kept that way.

**Comment by JordanMartinez** [comment]
There's another issue that came to mind recently. The identifiers we use in our bindings don't always make it clear which Node API is being used in the FFI. In other words, if someone wanted to look at the docs for a given PS identifier, they would need to look at the source code, look at the FFI source code, and then look at the corresponding Node docs for that identifier.

**Comment by thomashoneyman** [comment]
Would you mind describing how these breaking changes would affect a typical user of this library? Unless I’m explicitly using the MonadBuffer class, is there anything I’d need to do?

**Comment by JordanMartinez** [comment]
If one is using one of the data constructors from `Encoding` that I removed, they would need to update the removed ctor used to the one it aliases. Similarly, if they are any places doing an exhaustive pattern match without a wildcard for encoding, it would need to account for the new ctor, `Base64Url`.

**Comment by JordanMartinez** [comment]
Anupam looked at this code and suggested not inverting the module dependency for the `MonadBuffer` class. Instead, to deal with the type inference issue for this problem, we could export the implementations used in the `MonadBuffer` instances. The breakage here would be that `Buffer.create`'s type signature would change:
```diff
-create :: forall m b. MonadBuffer b m => m b
+create :: Effect Buffer
```

In other words, `Node.Buffer` would stop reexporting the members from `MonadBuffer` and instead export its own monomorphic functions that are used to implement `Buffer` instance for that type class.

Also, I think for ease of review, this PR should be broken up into smaller ones (you know, actually "do the right thing" when it comes to contributing to open source).

**Comment by JordanMartinez** [comment]
@thomashoneyman See #52

**Comment by JordanMartinez** [comment]
Superceded by #52, #53, #54, #55 (and a future PR for the Encoding change, which may be undesired).

**Pull request closed without merging**
